import base64
import io
import json
import os

import requests
from PIL import Image


GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")
GEMINI_API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"


def _get_env_value(name):
    value = os.environ.get(name, "")
    if value:
        return value
    env_path = os.path.join(os.path.dirname(__file__), ".env")
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line.startswith(f"{name}="):
                    return line.split("=", 1)[1].strip()
    return ""


def get_api_key():
    return _get_env_value("GEMINI_API_KEY")


def _clean_error(exc):
    """Never leak the API key in error messages."""
    resp = getattr(exc, "response", None)
    if resp is not None:
        try:
            msg = resp.json().get("error", {}).get("message", "")
            if msg:
                return msg
        except ValueError:
            pass
    text = str(exc)
    return text.split("?key=")[0].rstrip("& ")


def verify_caption(image_path, original_caption, corrected_caption):
    api_key = get_api_key()
    if not api_key:
        return {"error": "GEMINI_API_KEY not set. Add it to webapp/.env or environment variable."}

    with Image.open(image_path) as img:
        max_dim = 1024
        if max(img.size) > max_dim:
            img.thumbnail((max_dim, max_dim), Image.LANCZOS)
        buf = io.BytesIO()
        img.convert("RGB").save(buf, format="JPEG", quality=85)
        image_data = base64.b64encode(buf.getvalue()).decode("utf-8")

    ext = os.path.splitext(image_path)[1].lower()
    mime = {"jpg": "image/jpeg", "jpeg": "image/jpeg", "png": "image/png",
            "bmp": "image/bmp", "webp": "image/webp", "gif": "image/gif"}.get(ext.lstrip("."), "image/jpeg")

    prompt = f"""You are an image captioning expert. Compare these two captions for the same image:

Original caption (generated by AI): "{original_caption}"
Corrected caption (provided by human): "{corrected_caption}"

Analyze:
1. Is the corrected caption MORE accurate than the original? Consider: objects, actions, colors, numbers, spatial relationships, and overall scene description.
2. Is the corrected caption grammatically correct and natural?

Respond in JSON format only:
{{"verified": true/false, "reason": "brief explanation"}}"""

    payload = {
        "contents": [{"parts": [
            {"text": prompt},
            {"inline_data": {"mime_type": mime, "data": image_data}},
        ]}],
        "generationConfig": {"temperature": 0.2, "maxOutputTokens": 2048},
    }

    try:
        # Key sent via header so it never appears in URLs or error messages
        resp = requests.post(
            GEMINI_API_URL,
            json=payload,
            headers={"x-goog-api-key": api_key},
            timeout=120,
        )
        resp.raise_for_status()
        data = resp.json()

        parts = data["candidates"][0]["content"]["parts"]
        text = "".join(p.get("text", "") for p in parts).strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        result = json.loads(text.strip())
        if "verified" not in result:
            return {"error": f"Gemini response missing 'verified': {result}"}
        return result
    except requests.RequestException as e:
        return {"error": f"Gemini API error: {_clean_error(e)}"}
    except (KeyError, IndexError, json.JSONDecodeError) as e:
        return {"error": f"Gemini response parse error: {e}"}
